<!DOCTYPE html>
<html lang="es">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>HinchadasRank - ¿Quién tiene más aguante?</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css" rel="stylesheet">

    <link rel="stylesheet" href="css/style.css">
</head>

<body class="bg-light">

    <nav class="navbar navbar-expand-lg navbar-dark bg-dark shadow-sm">
        <div class="container">
            <a class="navbar-brand fw-bold" href="home">⚽ HinchadasRank</a>
            <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav">
                <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="navbarNav">
                <ul class="navbar-nav ms-auto">
                    <li class="nav-item">
                        <a class="nav-link" href="duelo">Duelo</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="ranking">Ranking</a>
                    </li>

                    <?php if (isset($_SESSION['ID_USER'])): ?>
                        <!-- Opciones para usuarios LOGUEADOS -->

                        <?php if ($_SESSION['ROL'] == 'ADMIN'): ?>
                            <li class="nav-item">
                                <a class="nav-link text-danger fw-bold" href="admin">Panel Admin</a>
                            </li>
                        <?php else: ?>
                            <li class="nav-item">
                                <a class="nav-link text-warning" href="perfil">Mi Perfil</a>
                            </li>
                        <?php endif; ?>

                        <li class="nav-item">
                            <a class="nav-link text-secondary" href="cerrarSesion">Cerrar Sesión</a>
                        </li>

                    <?php else: ?>
                        <!-- Opción para invitados -->
                        <li class="nav-item">
                            <a class="nav-link text-warning" href="inicioSesion">Iniciar Sesion</a>
                        </li>
                    <?php endif; ?>
                </ul>
            </div>
        </div>
    </nav>

    <main class="container my-4">
